create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nom text not null,
  entreprise text default 'Non renseignee',
  email text not null unique,
  telephone text not null,
  ville text default 'Non renseignee',
  statut text not null default 'en_attente' check (statut in ('en_attente', 'actif', 'refuse', 'suspendu')),
  discussion boolean not null default false,
  photo text,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.clients enable row level security;
