-- CyberCanvas Services - mise a niveau table routers
-- A executer dans Supabase Dashboard > SQL Editor.
-- Ces colonnes permettent de conserver les champs du formulaire
-- Nouveau Routeur / Modification Routeur apres actualisation.

alter table public.routers
  add column if not exists description text,
  add column if not exists systeme text default 'MIKROTIK',
  add column if not exists dns_name text default 'wifi.cybercanvas.local',
  add column if not exists adresse text;

update public.routers
set
  description = coalesce(description, 'Point WiFi MikroTik'),
  systeme = coalesce(systeme, 'MIKROTIK'),
  dns_name = coalesce(dns_name, 'wifi.cybercanvas.local'),
  adresse = coalesce(adresse, token)
where
  description is null
  or systeme is null
  or dns_name is null
  or adresse is null;

-- Configuration globale CyberCanvas Services
create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz default now()
);

insert into public.app_settings (key, value)
values
  ('support_whatsapp_local', '70693326'),
  ('support_whatsapp_full', '+22870693326'),
  ('support_whatsapp_link', 'https://wa.me/22870693326')
on conflict (key)
do update set
  value = excluded.value,
  updated_at = now();

-- Demandes de retrait portefeuille
create table if not exists public.retraits (
  id bigint generated by default as identity primary key,
  user_id uuid,
  nom text not null,
  montant numeric not null check (montant >= 5000),
  commission numeric not null default 0,
  net numeric not null default 0,
  statut text not null default 'en_attente'
    check (statut in ('en_attente', 'valide', 'refuse')),
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.retraits
  add column if not exists commission numeric not null default 0,
  add column if not exists net numeric not null default 0;

insert into public.app_settings (key, value)
values
  ('commission_retrait_percent', '10'),
  ('retrait_minimum_fcfa', '5000')
on conflict (key)
do update set
  value = excluded.value,
  updated_at = now();
