create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nom text not null,
  entreprise text default 'Non renseignee',
  email text not null unique,
  telephone text not null,
  ville text default 'Non renseignee',
  statut text not null default 'en_attente' check (statut in ('en_attente', 'actif', 'refuse', 'suspendu')),
  discussion boolean not null default false,
  photo text,
  email_verified boolean not null default false,
  verification_token_hash text unique,
  verification_expires_at timestamptz,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.clients enable row level security;

alter table public.clients
  add column if not exists email_verified boolean not null default false,
  add column if not exists verification_token_hash text unique,
  add column if not exists verification_expires_at timestamptz;

create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.password_reset_requests enable row level security;
