-- Migration CyberCanvas : remplacement de Cloudflare D1 par Supabase.
-- A executer dans Supabase > SQL Editor avant le deploiement du code.

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  profil_id bigint not null references public.profils(id) on delete cascade,
  owner_email text,
  username text not null,
  password text not null,
  statut text not null default 'disponible' check (statut in ('disponible', 'vendu', 'reserve', 'expire')),
  sale_identifier text unique,
  sold_at timestamptz,
  created_at timestamptz not null default now(),
  unique (profil_id, username)
);

create index if not exists idx_tickets_profil_id on public.tickets(profil_id);
create index if not exists idx_tickets_owner_email on public.tickets(owner_email);
create index if not exists idx_tickets_statut on public.tickets(statut);

create table if not exists public.shop_products (
  id bigint generated by default as identity primary key,
  nom text not null,
  description text not null default '',
  categorie text not null default 'Équipements réseau',
  prix integer not null check (prix > 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.shop_products(id),
  quantite integer not null default 1 check (quantite > 0),
  montant integer not null check (montant > 0),
  nom_client text not null,
  telephone text not null,
  email text,
  adresse text not null,
  ville text not null,
  note text,
  statut text not null default 'en_attente' check (statut in ('en_attente', 'paye', 'en_preparation', 'expedie', 'livre', 'annule')),
  payment_identifier text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists idx_shop_orders_status on public.shop_orders(statut);
create index if not exists idx_shop_orders_created_at on public.shop_orders(created_at desc);

alter table public.tickets enable row level security;
alter table public.shop_products enable row level security;
alter table public.shop_orders enable row level security;

-- Les routes serveur utilisent la clé service_role et appliquent les contrôles d'accès.
