-- =============================================================================
-- CyberCanvas Services - MIGRATION COMPLETE (unique script)
-- =============================================================================
-- Execute TOUTES les migrations Supabase dans l'ordre (001 -> 006).
-- Idempotent : peut etre relance sans risque.
-- A executer une seule fois dans Supabase Dashboard > SQL Editor.
--
-- Table des matieres :
--   Partie 1 (001) - tables de base + colonnes owner_email + index
--   Partie 2 (002) - retraits + activity_logs
--   Partie 3 (003) - colonnes routeurs + app_settings
--   Partie 4 (004) - RLS + vue publique public_profils
--   Partie 5 (005) - tickets + boutique (shop_products/shop_orders) + fonctions RPC
--   Partie 6 (006) - RLS sur les nouvelles tables
--   Partie 7       - verification finale RLS (lecture seule)
-- =============================================================================

-- =============================================================================
-- PARTIE 1 - base schema (001_base_schema.sql)
-- =============================================================================

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nom text not null,
  entreprise text default 'Non renseignee',
  email text not null unique,
  telephone text not null,
  ville text default 'Non renseignee',
  statut text not null default 'en_attente' check (statut in ('en_attente', 'actif', 'refuse', 'suspendu')),
  discussion boolean not null default false,
  photo text,
  email_verified boolean not null default false,
  verification_token_hash text unique,
  verification_expires_at timestamptz,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.routers (
  id bigint generated by default as identity primary key,
  nom text not null,
  description text,
  systeme text default 'MIKROTIK',
  dns_name text default 'wifi.cybercanvas.local',
  adresse text,
  token text not null default '',
  statut text not null default 'offline',
  credits integer not null default 0,
  owner_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.profils (
  id bigint generated by default as identity primary key,
  nom text not null,
  prix integer not null default 0,
  duree text not null default '',
  slug text not null default '',
  owner_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.ventes (
  id bigint generated by default as identity primary key,
  profil_id bigint not null,
  ticket_id bigint not null,
  montant numeric not null default 0,
  telephone text not null default '',
  statut text not null default 'paye',
  owner_email text,
  created_at timestamptz not null default now()
);

alter table public.routers add column if not exists owner_email text;
alter table public.profils add column if not exists owner_email text;
alter table public.ventes add column if not exists owner_email text;

create index if not exists idx_routers_owner_email on public.routers(owner_email);
create index if not exists idx_profils_owner_email on public.profils(owner_email);
create index if not exists idx_ventes_owner_email on public.ventes(owner_email);
create index if not exists idx_ventes_created_at on public.ventes(created_at desc);

-- =============================================================================
-- PARTIE 2 - retraits + activity_logs (002_retraits_activity.sql)
-- =============================================================================

create table if not exists public.retraits (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  client_nom text not null default '',
  client_telephone text not null default '',
  numero_paiement text not null,
  montant integer not null check (montant >= 2000),
  commission integer not null default 0,
  net integer not null default 0,
  statut text not null default 'en_attente' check (statut in ('en_attente', 'valide', 'refuse')),
  note_admin text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.retraits
  add column if not exists owner_email text,
  add column if not exists client_nom text not null default '',
  add column if not exists client_telephone text not null default '',
  add column if not exists numero_paiement text,
  add column if not exists note_admin text;

create index if not exists idx_retraits_owner_email on public.retraits(owner_email);
create index if not exists idx_retraits_statut on public.retraits(statut);
create index if not exists idx_retraits_created_at on public.retraits(created_at desc);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_email text,
  owner_email text,
  role text not null default 'systeme',
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_logs_owner_email on public.activity_logs(owner_email);
create index if not exists idx_activity_logs_action on public.activity_logs(action);
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);

-- =============================================================================
-- PARTIE 3 - colonnes routeurs + app_settings (003_app_settings_routers.sql)
-- =============================================================================

alter table public.routers
  add column if not exists description text,
  add column if not exists systeme text default 'MIKROTIK',
  add column if not exists dns_name text default 'wifi.cybercanvas.local',
  add column if not exists adresse text;

update public.routers
set
  description = coalesce(description, 'Point WiFi MikroTik'),
  systeme = coalesce(systeme, 'MIKROTIK'),
  dns_name = coalesce(dns_name, 'wifi.cybercanvas.local'),
  adresse = coalesce(adresse, token);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz default now()
);

insert into public.app_settings (key, value)
values
  ('support_whatsapp_local', '70693326'),
  ('support_whatsapp_full', '+22870693326'),
  ('support_whatsapp_link', 'https://wa.me/22870693326'),
  ('commission_retrait_percent', '10'),
  ('retrait_minimum_fcfa', '5000')
on conflict (key)
do update set
  value = excluded.value,
  updated_at = now();

-- =============================================================================
-- PARTIE 4 - RLS + vue publique (004_rls.sql)
-- =============================================================================

alter table public.clients enable row level security;
alter table public.password_reset_requests enable row level security;
alter table public.routers enable row level security;
alter table public.profils enable row level security;
alter table public.ventes enable row level security;
alter table public.retraits enable row level security;
alter table public.activity_logs enable row level security;

drop view if exists public.public_profils;
create view public.public_profils as
  select id, nom, prix, duree, slug
  from public.profils;

revoke all on public.public_profils from anon, authenticated;
grant select on public.public_profils to anon, authenticated;

-- =============================================================================
-- PARTIE 5 - tickets + boutique + fonctions RPC (005_shop_tickets_rpc.sql)
-- =============================================================================

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  profil_id bigint not null,
  owner_email text,
  username text not null,
  password text not null,
  statut text not null default 'disponible' check (statut in ('disponible', 'vendu', 'reserve', 'expire')),
  sale_identifier text unique,
  sold_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_tickets_profil_username on public.tickets (profil_id, username);
create index if not exists idx_tickets_profil_statut on public.tickets (profil_id, statut);
create index if not exists idx_tickets_owner_email on public.tickets (owner_email);

alter table public.ventes
  add column if not exists sale_identifier text;

create unique index if not exists idx_ventes_sale_identifier on public.ventes (sale_identifier);

create table if not exists public.shop_products (
  id bigint generated by default as identity primary key,
  nom text not null,
  description text not null default '',
  categorie text not null default 'Équipements réseau',
  prix integer not null,
  stock integer not null default 0,
  image_url text,
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  quantite integer not null default 1,
  montant integer not null,
  nom_client text not null,
  telephone text not null,
  email text,
  adresse text not null,
  ville text not null,
  note text,
  statut text not null default 'en_attente' check (statut in ('en_attente', 'paye', 'en_preparation', 'expedie', 'livre', 'annule')),
  payment_identifier text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists idx_shop_orders_product on public.shop_orders (product_id);
create index if not exists idx_shop_orders_statut on public.shop_orders (statut);

-- Vente atomique d'un ticket : marque 'vendu' + enregistre la vente.
-- Retourne le ticket vendu (id, username, password, profil_id) ou null si aucun ticket.
-- Idempotent : un meme identifier ne produit qu'une seule vente.
create or replace function public.sell_ticket(
  p_identifier text,
  p_profil_id bigint,
  p_montant integer,
  p_telephone text,
  p_owner_email text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ticket public.tickets%rowtype;
begin
  select *
  into v_ticket
  from public.tickets
  where sale_identifier = p_identifier and statut = 'vendu'
  limit 1;

  if v_ticket.id is not null then
    insert into public.ventes (profil_id, ticket_id, montant, telephone, statut, owner_email, sale_identifier)
    values (v_ticket.profil_id, v_ticket.id, p_montant, coalesce(p_telephone, ''), 'paye', p_owner_email, p_identifier)
    on conflict (sale_identifier) do nothing;

    return jsonb_build_object(
      'id', v_ticket.id,
      'username', v_ticket.username,
      'password', v_ticket.password,
      'profil_id', v_ticket.profil_id
    );
  end if;

  select *
  into v_ticket
  from public.tickets
  where profil_id = p_profil_id and statut = 'disponible'
  order by id asc
  limit 1
  for update skip locked;

  if v_ticket.id is null then
    return null;
  end if;

  update public.tickets
  set statut = 'vendu', sale_identifier = p_identifier, sold_at = now()
  where id = v_ticket.id;

  insert into public.ventes (profil_id, ticket_id, montant, telephone, statut, owner_email, sale_identifier)
  values (v_ticket.profil_id, v_ticket.id, p_montant, coalesce(p_telephone, ''), 'paye', p_owner_email, p_identifier)
  on conflict (sale_identifier) do nothing;

  return jsonb_build_object(
    'id', v_ticket.id,
    'username', v_ticket.username,
    'password', v_ticket.password,
    'profil_id', v_ticket.profil_id
  );
end;
$$;

-- Confirmation atomique d'une commande boutique : payee + stock decremente.
create or replace function public.confirm_shop_payment(
  p_identifier text,
  p_order_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.shop_orders%rowtype;
begin
  select *
  into v_order
  from public.shop_orders
  where id = p_order_id and payment_identifier = p_identifier
  limit 1;

  if v_order.id is null then
    return jsonb_build_object('ok', false, 'message', 'Commande invalide');
  end if;

  if v_order.statut in ('paye', 'en_preparation', 'expedie', 'livre') then
    return jsonb_build_object('ok', true, 'message', 'Paiement deja confirme');
  end if;

  update public.shop_orders
  set statut = 'paye', paid_at = now()
  where id = p_order_id;

  update public.shop_products
  set stock = greatest(stock - v_order.quantite, 0), updated_at = now()
  where id = v_order.product_id;

  return jsonb_build_object('ok', true, 'message', 'Paiement confirme');
end;
$$;

-- =============================================================================
-- PARTIE 6 - RLS sur les nouvelles tables (006_rls_tickets_shop.sql)
-- =============================================================================

alter table public.tickets enable row level security;
alter table public.shop_products enable row level security;
alter table public.shop_orders enable row level security;

-- aucune policy : acces refuse par defaut pour anon et authenticated

-- =============================================================================
-- PARTIE 7 - verification finale RLS (lecture seule)
-- =============================================================================

select
  schemaname,
  tablename,
  rowsecurity
from pg_tables
where schemaname = 'public'
order by tablename;

select
  schemaname,
  tablename,
  policyname,
  cmd,
  roles
from pg_policies
where schemaname = 'public'
order by tablename, policyname;

-- Fin de la migration complete.