-- CyberCanvas Services - migrations Supabase
-- 001_base_schema.sql
-- Tables de base + colonnes de propriete (owner_email) + index.
-- Idempotent : peut etre relance sans risque.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nom text not null,
  entreprise text default 'Non renseignee',
  email text not null unique,
  telephone text not null,
  ville text default 'Non renseignee',
  statut text not null default 'en_attente' check (statut in ('en_attente', 'actif', 'refuse', 'suspendu')),
  discussion boolean not null default false,
  photo text,
  email_verified boolean not null default false,
  verification_token_hash text unique,
  verification_expires_at timestamptz,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.routers (
  id bigint generated by default as identity primary key,
  nom text not null,
  description text,
  systeme text default 'MIKROTIK',
  dns_name text default 'wifi.cybercanvas.local',
  adresse text,
  token text not null default '',
  statut text not null default 'offline',
  credits integer not null default 0,
  owner_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.profils (
  id bigint generated by default as identity primary key,
  nom text not null,
  prix integer not null default 0,
  duree text not null default '',
  slug text not null default '',
  owner_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.ventes (
  id bigint generated by default as identity primary key,
  profil_id bigint not null,
  ticket_id bigint not null,
  montant numeric not null default 0,
  telephone text not null default '',
  statut text not null default 'paye',
  owner_email text,
  created_at timestamptz not null default now()
);

alter table public.routers add column if not exists owner_email text;
alter table public.profils add column if not exists owner_email text;
alter table public.ventes add column if not exists owner_email text;

-- Index sur owner_email : cree seulement si la colonne existe (une table
-- pre-existante avec un ancien schema pourrait ne pas l'avoir).
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'routers' and column_name = 'owner_email') then
    create index if not exists idx_routers_owner_email on public.routers(owner_email);
  end if;
end $$;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profils' and column_name = 'owner_email') then
    create index if not exists idx_profils_owner_email on public.profils(owner_email);
  end if;
end $$;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'ventes' and column_name = 'owner_email') then
    create index if not exists idx_ventes_owner_email on public.ventes(owner_email);
  end if;
end $$;

create index if not exists idx_ventes_created_at on public.ventes(created_at desc);