-- CyberCanvas Services - migrations Supabase
-- 005_shop_tickets_rpc.sql
-- Tables tickets / boutique (remplace Cloudflare D1) + fonctions RPC atomiques.
-- ventes existe deja (001) : on ajoute sale_identifier pour l'idempotence.
-- Idempotent : peut etre relance sans risque.

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  profil_id bigint not null,
  owner_email text,
  username text not null,
  password text not null,
  statut text not null default 'disponible' check (statut in ('disponible', 'vendu', 'reserve', 'expire')),
  sale_identifier text unique,
  sold_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_tickets_profil_username on public.tickets (profil_id, username);
create index if not exists idx_tickets_profil_statut on public.tickets (profil_id, statut);
create index if not exists idx_tickets_owner_email on public.tickets (owner_email);

alter table public.ventes
  add column if not exists sale_identifier text;

create unique index if not exists idx_ventes_sale_identifier on public.ventes (sale_identifier);

create table if not exists public.shop_products (
  id bigint generated by default as identity primary key,
  nom text not null,
  description text not null default '',
  categorie text not null default 'Équipements réseau',
  prix integer not null,
  stock integer not null default 0,
  image_url text,
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  quantite integer not null default 1,
  montant integer not null,
  nom_client text not null,
  telephone text not null,
  email text,
  adresse text not null,
  ville text not null,
  note text,
  statut text not null default 'en_attente' check (statut in ('en_attente', 'paye', 'en_preparation', 'expedie', 'livre', 'annule')),
  payment_identifier text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists idx_shop_orders_product on public.shop_orders (product_id);
create index if not exists idx_shop_orders_statut on public.shop_orders (statut);

-- Vente atomique d'un ticket : marque 'vendu' + enregistre la vente.
-- Retourne le ticket vendu (id, username, password, profil_id) ou null si aucun ticket.
-- Idempotent : un meme identifier ne produit qu'une seule vente.
create or replace function public.sell_ticket(
  p_identifier text,
  p_profil_id bigint,
  p_montant integer,
  p_telephone text,
  p_owner_email text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ticket public.tickets%rowtype;
begin
  select *
  into v_ticket
  from public.tickets
  where sale_identifier = p_identifier and statut = 'vendu'
  limit 1;

  if v_ticket.id is not null then
    insert into public.ventes (profil_id, ticket_id, montant, telephone, statut, owner_email, sale_identifier)
    values (v_ticket.profil_id, v_ticket.id, p_montant, coalesce(p_telephone, ''), 'paye', p_owner_email, p_identifier)
    on conflict (sale_identifier) do nothing;

    return jsonb_build_object(
      'id', v_ticket.id,
      'username', v_ticket.username,
      'password', v_ticket.password,
      'profil_id', v_ticket.profil_id
    );
  end if;

  select *
  into v_ticket
  from public.tickets
  where profil_id = p_profil_id and statut = 'disponible'
  order by id asc
  limit 1
  for update skip locked;

  if v_ticket.id is null then
    return null;
  end if;

  update public.tickets
  set statut = 'vendu', sale_identifier = p_identifier, sold_at = now()
  where id = v_ticket.id;

  insert into public.ventes (profil_id, ticket_id, montant, telephone, statut, owner_email, sale_identifier)
  values (v_ticket.profil_id, v_ticket.id, p_montant, coalesce(p_telephone, ''), 'paye', p_owner_email, p_identifier)
  on conflict (sale_identifier) do nothing;

  return jsonb_build_object(
    'id', v_ticket.id,
    'username', v_ticket.username,
    'password', v_ticket.password,
    'profil_id', v_ticket.profil_id
  );
end;
$$;

-- Confirmation atomique d'une commande boutique : payee + stock decremente.
create or replace function public.confirm_shop_payment(
  p_identifier text,
  p_order_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.shop_orders%rowtype;
begin
  select *
  into v_order
  from public.shop_orders
  where id = p_order_id and payment_identifier = p_identifier
  limit 1;

  if v_order.id is null then
    return jsonb_build_object('ok', false, 'message', 'Commande invalide');
  end if;

  if v_order.statut in ('paye', 'en_preparation', 'expedie', 'livre') then
    return jsonb_build_object('ok', true, 'message', 'Paiement deja confirme');
  end if;

  update public.shop_orders
  set statut = 'paye', paid_at = now()
  where id = p_order_id;

  update public.shop_products
  set stock = greatest(stock - v_order.quantite, 0), updated_at = now()
  where id = v_order.product_id;

  return jsonb_build_object('ok', true, 'message', 'Paiement confirme');
end;
$$;