import { NextRequest, NextResponse } from "next/server";
import { verifyAdminSession } from "@/lib/admin-session";
import { getSupabaseAdminClient } from "@/lib/supabase-server";
type Summary = { email: string; routeurs: number; routeursOnline: number; profils: number; ticketsDisponibles: number; ticketsVendus: number; ventes: number; revenus: number; commission: number; net: number; retraits: number; retraitsEnAttente: number; retraitsValides: number; montantRetraitsNet: number; derniereActivite: string | null; details: { routeurs: unknown[]; profils: unknown[]; ventesRecentes: unknown[] } };
const empty = (email: string): Summary => ({ email, routeurs: 0, routeursOnline: 0, profils: 0, ticketsDisponibles: 0, ticketsVendus: 0, ventes: 0, revenus: 0, commission: 0, net: 0, retraits: 0, retraitsEnAttente: 0, retraitsValides: 0, montantRetraitsNet: 0, derniereActivite: null, details: { routeurs: [], profils: [], ventesRecentes: [] } });
const norm = (value: unknown) => String(value || "").trim().toLowerCase();
export async function GET(request: NextRequest) {
  if (!(await verifyAdminSession(request.cookies.get("admin_session")?.value))) return NextResponse.json({ message: "Non autorisé." }, { status: 401 });
  const supabase = getSupabaseAdminClient();
  if (!supabase) return NextResponse.json({ message: "Configuration Supabase serveur manquante." }, { status: 500 });
  const summaries = new Map<string, Summary>();
  const get = (email: unknown) => { const key = norm(email); if (!key) return null; if (!summaries.has(key)) summaries.set(key, empty(key)); return summaries.get(key) || null; };
  const [{ data: clients }, { data: routers }, { data: profiles }, { data: sales }, { data: withdrawals }, { data: tickets }] = await Promise.all([supabase.from("clients").select("email"), supabase.from("routers").select("id, owner_email, nom, systeme, dns_name, adresse, statut, credits"), supabase.from("profils").select("id, owner_email, nom, prix, duree, slug"), supabase.from("ventes").select("id, owner_email, montant, telephone, statut, created_at, profils(nom)"), supabase.from("retraits").select("id, owner_email, montant, commission, net, statut, created_at"), supabase.from("tickets").select("owner_email, profil_id, statut")]);
  (clients || []).forEach((row) => get(row.email));
  const profileOwners = new Map<number, string>();
  const profileDetails = new Map<number, { id: number; nom: string; prix: number; duree: string; slug: string; ticketsDisponibles: number; ticketsVendus: number; revenus: number; ventes: number }>();
  (routers || []).forEach((row) => { const summary = get(row.owner_email); if (!summary) return; summary.routeurs += 1; if (String(row.statut).toLowerCase() === "online") summary.routeursOnline += 1; summary.details.routeurs.push({ id: row.id, nom: row.nom || "Routeur sans nom", systeme: row.systeme || "MIKROTIK", dnsName: row.dns_name || "-", adresse: row.adresse || "-", statut: row.statut || "offline", credits: Number(row.credits || 0) }); });
  (profiles || []).forEach((row) => { const summary = get(row.owner_email); if (!summary) return; const detail = { id: row.id, nom: row.nom || "Profil sans nom", prix: Number(row.prix || 0), duree: row.duree || "-", slug: row.slug || "", ticketsDisponibles: 0, ticketsVendus: 0, revenus: 0, ventes: 0 }; summary.profils += 1; profileOwners.set(row.id, summary.email); profileDetails.set(row.id, detail); summary.details.profils.push(detail); });
  (sales || []).forEach((row) => { const summary = get(row.owner_email); if (!summary) return; const amount = Number(row.montant || 0); summary.ventes += 1; summary.revenus += amount; summary.derniereActivite = row.created_at || summary.derniereActivite; const profileName = row.profils?.[0]?.nom || "Profil inconnu"; const detail = summary.details.profils.find((item) => (item as { nom?: string }).nom === profileName) as { ventes: number; revenus: number } | undefined; if (detail) { detail.ventes += 1; detail.revenus += amount; } summary.details.ventesRecentes.push({ id: row.id, profil: profileName, montant: amount, telephone: row.telephone || "-", statut: row.statut || "paye", createdAt: row.created_at || null }); });
  (withdrawals || []).forEach((row) => { const summary = get(row.owner_email); if (!summary) return; summary.retraits += 1; summary.montantRetraitsNet += Number(row.net || 0); summary.derniereActivite = row.created_at || summary.derniereActivite; if (row.statut === "valide") summary.retraitsValides += 1; if (row.statut === "en_attente") summary.retraitsEnAttente += 1; });
  (tickets || []).forEach((row) => { const owner = norm(row.owner_email) || profileOwners.get(Number(row.profil_id)) || ""; const summary = get(owner); if (!summary) return; const detail = profileDetails.get(Number(row.profil_id)); if (String(row.statut).toLowerCase() === "vendu") { summary.ticketsVendus += 1; if (detail) detail.ticketsVendus += 1; } else { summary.ticketsDisponibles += 1; if (detail) detail.ticketsDisponibles += 1; } });
  summaries.forEach((summary) => { summary.commission = Math.round(summary.revenus * 0.1); summary.net = Math.max(summary.revenus - summary.commission, 0); summary.details.ventesRecentes = summary.details.ventesRecentes.slice(-8).reverse(); });
  return NextResponse.json({ activities: Array.from(summaries.values()).sort((a, b) => a.email.localeCompare(b.email)) });
}
